# Generated by Django 6.0.2 on 2026-02-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'period_month', 'period_year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Net Salary', 'Net Salary'), ('Allowance', 'Allowance'), ('Incentive', 'Incentive'), ('Beneficial', 'Beneficial'), ('Contribution', 'Contribution'), ('Deduction', 'Deduction')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reimbursement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='payroll.payrollrecord')),
            ],
        ),
    ]
