# Generated by Django 6.0.2 on 2026-02-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('category', models.CharField(max_length=100)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Awaiting', 'Awaiting'), ('Rejected', 'Rejected')], default='Awaiting', max_length=20)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to='core.employee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='core.employee')),
            ],
        ),
    ]
